# docker Compose defines and orchestrates all containers required by Inception.
# it builds each service from its dockerfile and manages how containers share networks, 
# volumes, env variables, secrets, ports and dependencies.

services:

  # MDB stores the WP database.
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wp_database_store:/var/lib/mysql
    networks:
      - inception_bridge
    expose:
      - "${MDB_PORT}"
    secrets:
      - db_root_password
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h localhost -u rmedeiro -p$$(cat /run/secrets/db_password) -e 'SELECT 1' >/dev/null 2>&1"]
      interval: 1s
      timeout: 2s
      retries: 30

  # WP runs with PHP-FPM and stores its files in a persistent volume.
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wp_content_store:/var/www/html
    networks:
      - inception_bridge
    expose:
      - "${PHP_FPM_PORT}"
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grep", "-q", "php-fpm", "/proc/1/cmdline"]
      interval: 1s
      timeout: 2s
      retries: 30

  # NGINX is the main HTTPS entry point and the only web service exposed on port 443.
  # it serves WP and proxies requests to the internal bonus web services.
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - wp_content_store:/var/www/html
    networks:
      - inception_bridge
    env_file:
      - .env
    depends_on:
      wordpress:
        condition: service_healthy

  # Redis provides an in-memory object cache for WP.
  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis
    container_name: redis
    restart: on-failure
    env_file:
      - .env
    networks:
      - inception_bridge
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 30

  # Adminer provides a web interface for MariaDB.
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer
    container_name: adminer
    restart: on-failure
    env_file:
      - .env
    expose:
      - "8080"
    networks:
      - inception_bridge
    depends_on:
      mariadb:
        condition: service_healthy

  # FTP provides remote access to the persistent WordPress files.
  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp
    container_name: ftp
    restart: on-failure
    env_file:
      - .env
    secrets:
      - ftp_password
    volumes:
      - wp_content_store:/var/www/html
    networks:
      - inception_bridge
    ports:
      - "21:21"
      - "40000-40010:40000-40010"
    depends_on:
      - wordpress

  # Static serves an independent HTML, CSS and JavaScript website.
  # Port 8081 is internal because NGINX proxies /static/ requests to this service.
  static:
    build:
      context: ./requirements/bonus/static
      dockerfile: Dockerfile
    image: static
    container_name: static
    restart: on-failure
    env_file:
      - .env
    expose:
      - "8081"
    networks:
      - inception_bridge

  # Portainer provides a web interface for Docker management.
  portainer:
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    image: portainer
    container_name: portainer
    restart: on-failure
    env_file:
      - .env
    volumes:
      - portainer_store:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception_bridge
    expose:
      - "9000"

# Volumes provide persistent storage outside the containers.
# Docker manages the volume names, while bind mounts store the actual data
volumes:

  # Stores MDB database files persistently.
  wp_database_store:
    name: wp_database_store
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

  # Stores WP files persistently and allows the same files to be shared between WP, NGINX and FTP.
  wp_content_store:
    name: wp_content_store
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

  portainer_store:
    name: portainer_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/portainer


# bridge network creates a private network shared by the containers.
# containers connected to it can communicate using their service names, without exposing 
# internal service ports directly to the host.
networks:

  inception_bridge:
    # Bridge creates an isolated network on the Docker host while allowing communication 
    # between connected containers.
    driver: bridge


# secrets keep sensitive credentials outside dockerfiles and source code.
# docker makes each secret available inside the required container as a file instead of 
# storing passwords directly in environment variables.
secrets:

  db_root_password:
    file: ../secrets/db_root_password.txt

  db_password:
    file: ../secrets/db_password.txt

  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

  wp_user_password:
    file: ../secrets/wp_user_password.txt

  ftp_password:
    file: ../secrets/ftp_password.txt
