#!/bin/bash

# Stop the script immediately if any command fails.
set -e

# Directory where NGINX stores SSL certificates.
NGINX_SSL_DIR="/etc/nginx/ssl"

# Directory where NGINX reads server configuration files.
NGINX_CONFIG_DIR="/etc/nginx/conf.d"

# Custom NGINX configuration generated by this script. Will contain the server configuration for the WordPress site.
NGINX_CONFIG_FILE="$NGINX_CONFIG_DIR/default.conf"

# SSL certificate and key used for HTTPS.
NGINX_SSL_CERT="$NGINX_SSL_DIR/inception.crt"
NGINX_SSL_KEY="$NGINX_SSL_DIR/inception.key"

echo "[NGINX] >> Checking required environment variables..."
if [ -z "$DOMAIN_NAME" ] || [ -z "$PHP_FPM_HOST" ]; then
	echo "[ERROR] >> DOMAIN_NAME, PHP_FPM_HOST or PHP_FPM_PORT is missing."
	exit 1
fi

# Create required NGINX directories if they do not already exist.
mkdir -p "$NGINX_SSL_DIR"
mkdir -p "$NGINX_CONFIG_DIR"

# Creates a SSL certificate for the NGINX server. This allows the server to serve content over HTTPS.
echo "[NGINX] >> Creating SSL certificate..."
if [ ! -f "$NGINX_SSL_CERT" ] || [ ! -f "$NGINX_SSL_KEY" ]; then
	openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "$NGINX_SSL_KEY" -out "$NGINX_SSL_CERT" \
		-subj "/C=PT/ST=Lisbon/L=Lisbon/O=42/OU=Inception/CN=${DOMAIN_NAME}"
else
	echo "[NGINX] >> SSL certificate already exists. Reusing existing certificate."
fi

# Creates the NGINX server configuration file with the necessary settings to serve the WordPress site.
# The configuration sets up a server block that listens on port 443 for HTTPS connections, serves content from the /var/www/html directory, 
# and forwards PHP requests to the PHP-FPM service defined by PHP_FPM_HOST.
echo "[NGINX] >> Creating NGINX configuration file..."
cat > "$NGINX_CONFIG_FILE" << EOF
server {

	# Listen on port 443 for HTTPS connections. The server will use the specified SSL certificate and key for secure communication.
	listen 443 ssl;

	# Listen on IPv6 as well to support clients connecting over IPv6. This allows the server to accept connections from both IPv4 and IPv6 clients.
	listen [::]:443 ssl;

	server_name ${DOMAIN_NAME};

	# Root directory for the server. NGINX will serve files from this directory when clients make requests to the server.
	root /var/www/html;
	index index.php index.html;

	ssl_certificate ${NGINX_SSL_CERT};
	ssl_certificate_key ${NGINX_SSL_KEY};

	ssl_protocols TLSv1.2 TLSv1.3;

	location / {
		try_files \$uri \$uri/ /index.php?\$args;
	}

	# This location block handles requests for PHP files. It forwards these requests to the PHP-FPM service defined by PHP_FPM_HOST on port 9000.
	location ~ \.php$ {
		include fastcgi_params;
		fastcgi_pass ${PHP_FPM_HOST}:9000;
		fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
	}

	location ~ /\.ht {
		deny all;
	}
}
EOF

echo "[NGINX] >> Starting NGINX in foreground..."
exec nginx -g "daemon off;"
