events
{
}

http
{
    server
    {
        listen 443 ssl;
        ssl_certificate /etc/nginx/ssl/certs/pub.crt;
        ssl_certificate_key /etc/nginx/ssl/private/priv.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        root /var/www/html;
        index index.html;
        location /
        {
            try_files $uri $uri/ =404;
        }
    }
}
